apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: react-ui
spec:
  selector:
    app: react-ui
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000